### ISSUE TITLE
Run command: make dist fail

### ISSUE THREAD

**Issue by EitanBe** [tmobile/stf_ios_support#12]
ERROR:
make: *** No rule to make target `repos/WebDriverAgent/package.json', needed by `repos/WebDriverAgent/Carthage/Checkouts/RoutingHTTPServer'.  Stop.

ENV:
Macbook 
OS: Mojave 10.14.5
node: 8

**Comment by nanoscopic** [comment]
The Makefile rule has been corrected and you should not see this problem any more. `git pull` the fixing update: https://github.com/tmobile/stf_ios_support/commit/ff059aa348d1b7397751d8664cfefaceab7430f5 and try again.

**Comment by EitanBe** [comment]
thank you

**Comment by EitanBe** [comment]
I pulled the latest code and it fixed the issue.
