### ISSUE TITLE
osx_ios_device_trigger fails to build due to signing

### ISSUE THREAD

**Issue by EitanBe** [tmobile/stf_ios_support#13]
Ins/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework: replacing existing signature
** TEST BUILD SUCCEEDED **

git clone https://github.com/tmobile/osx_ios_device_trigger.git repos/osx_ios_device_trigger
Cloning into 'repos/osx_ios_device_trigger'...
remote: Enumerating objects: 28, done.
remote: Counting objects: 100% (28/28), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 28 (delta 8), reused 23 (delta 7), pack-reused 0
Unpacking objects: 100% (28/28), done.
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C repos/osx_ios_device_trigger
xcodebuild -scheme osx_ios_device_trigger TARGET_BUILD_DIR="../../bin"
Build settings from command line:
TARGET_BUILD_DIR = ../../bin

note: Using new build system
note: Planning build
note: Constructing build description
error: No signing certificate "Mac Development" found: No "Mac Development" signing certificate matching team ID "##########" with a private key was found. (in target 'osx_ios_device_trigger' from project 'osx_ios_device_trigger')

** BUILD FAILED **

make[1]: *** [../../bin/osx_ios_device_trigger] Error 65
make: *** [bin/osx_ios_device_trigger] Error 2

**Comment by EitanBe** [comment]
Change it manually:
cd repos/osx_ios_device_trigger/
open osx_ios_device_trigger.xcodeproj/
change sign manually.
fixed the issue

**Comment by nanoscopic** [comment]
Agreeably enough you can work around the issue as stated, but it shouldn't occur to begin with. This is still a valid bug until proven that it doesn't happen on a clean system with a fresh clone.

**Comment by Slavianin** [comment]
have same problem on clean system

**Comment by nanoscopic** [comment]
Agreed. This was an issue; I have dropped the specified signing from the project file and it should now build correctly without manually altering anything via xcode. Pull and retry. ( you should also pull the main repo as video_enabler had the same issue )

`cd stf_ios_support`
`git pull`
`cd repos/osx_ios_device_trigger`
`git pull`
`cd ../..`
`make`
