### ISSUE TITLE
Makefile process is faulty for stf-ios-provider and offline/build_info.json

### ISSUE THREAD

**Issue by EitanBe** [tmobile/stf_ios_support#14]
$ make dist
/bin/sh: offline/build_info.json: No such file or directory
make: *** [offline/dist.tgz] Error 1

**Comment by EitanBe** [comment]
git clone https://github.com/nanoscopic/stf-ios-provider.git repos/stf-ios-provider --branch master
Cloning into 'repos/stf-ios-provider'...
remote: Enumerating objects: 98, done.
remote: Counting objects: 100% (98/98), done.
remote: Compressing objects: 100% (80/80), done.
remote: Total 98 (delta 10), reused 89 (delta 8), pack-reused 0
Unpacking objects: 100% (98/98), done.
go get github.com/fsnotify/fsnotify
go get github.com/sirupsen/logrus
go build view_log.go
/bin/sh: offline/build_info.json: No such file or directory
make: *** [offline/dist.tgz] Error 1
Ei

**Comment by nanoscopic** [comment]
The latest commits should fix this issue.
