### ISSUE TITLE
 storage-temp  Cannot create container for service storage-temp: invalid volume specification

### ISSUE THREAD

**Issue by bikeebh** [tmobile/stf_ios_support#18]
Hi
I am getting this error  

when i am running this command _sudo docker-compose up_  

from server folder 

/Users/bikee/Downloads/stf_ios_support/server

lab-mac-1:server radmin$ **pwd**
/Users/bikee/Downloads/stf_ios_support/server
lab-mac-1:server radmin$ ls -l
total 32
-rw-r--r--  1 bikee  staff   718 Feb 18 06:00 README.md
drwxr-xr-x  6 bikee  staff   192 Feb 18 06:00 cert
-rw-r--r--  1 bikee  staff  4304 Feb 18 06:00 docker-compose.yml
drwxr-xr-x  5 bikee  staff   160 Feb 18 06:00 nginx
-rw-r--r--  1 bikee  staff    21 Feb 18 06:00 runcli.js
drwxr-xr-x  3 bikee  staff    96 Feb 18 06:07 storage-temp
lab-mac-1:server bikee$ **sudo docker-compose up**
server_dev-triproxy_1 is up-to-date
Recreating 045510e654c5_server_storage-temp_1 ...
server_triproxy_1 is up-to-date
server_auth_1 is up-to-date
server_rethinkdb_1 is up-to-date
Recreating 045510e654c5_server_storage-temp_1 ... error
server_processor_1 is up-to-date

ERROR: for 045510e654c5_server_storage-temp_1  Cannot create container for service storage-temp: invalid volume specification: '49da00e670b30edada5509647a36fe43bb6b37ce9649Starting server_migrate_1                     ... done
server_api_1 is up-to-date
server_reaper_1 is up-to-date

ERROR: for storage-temp  Cannot create container for service storage-temp: invalid volume specification: '49da00e670b30edada5509647a36fe43bb6b37ce9649991f0c1c42e9a1856def:data:rw': invalid mount config for type "volume": invalid mount path: 'data' mount path must be absolute
ERROR: Encountered errors while bringing up the project.
lab-mac-1:server bikee$

**Comment by bikeebh** [comment]
Hi 

I fixed this issue 
above issue

now when i am running this i am getting this issue

lab-mac-1:stf_ios_support radmin$ ./run 
FATA[0000] 2 invalid character '/' looking for beginning of value

**Comment by nanoscopic** [comment]
The error given looks to be an error parsing the config.json file. My guess would be that you copied the `config.json.example` file to `config.json`, including the comment lines. Unfortunately, the JSON parser in Golang is not capable of parsing comment lines. ( lines starting `//` ) You will need to remove the comment line for the system to be able to parse the config file.

**Comment by nanoscopic** [comment]
You stated, "I fixed this issue". The '//' error is addressed and is due to copy pasting comment line.
I'm not clear what the issue was that you fixed so unsure what to do with this ticket otherwise. Closing.
