### ISSUE TITLE
./run -> repos/stf-ios-provider does not exist

### ISSUE THREAD

**Issue by bikeebh** [tmobile/stf_ios_support#22]
Hi 

When I am running (./run) getting this error when 

Unable to open file for writing: open logs/coordinator: no such file or directoryUnable to open file for writing: open logs/procs: no such file or directoryCannot write to logfile: invalid argumentFailed to fire hook: invalid argument
INFO[0000] Process start - device_trigger                proc=device_trigger type=proc_start
INFO[0000] Process start - video_enabler                 proc=video_enabler type=proc_start
INFO[0000] Process start - stf_provider                  client_hostname=radmins-Mac-mini.local client_ip=172.16.50.111 proc=stf_provider server_hostname=radmins-Mac-mini.local server_ip=172.16.50.111 type=proc_start
**ERRO[0000] Error starting stf                            error="chdir ./repos/stf-ios-provider: no such file or directory" proc=stf_provider type=proc_err**
WARN[0000] Process end - stf_provider                    proc=stf_provider type=proc_end

**Comment by nanoscopic** [comment]
From the error messages, it appears that you do not have a `logs` directory in the directory you are running `./run` from. It also appears you do not have a `./repos/stf-ios-provider` in the directory either.

Considering that the repo itself, `stf-ios-support`, has a `logs` directory, the error messages seem to imply that your clone is incomplete, or that your current working directory is not the root of the cloned repo when you run `./run`.

The `./repos/stf-ios-provider` directory is cloned down when you run `make`. Have you run `make` before attempting to run `./run`?
