### ISSUE TITLE
WebDriverAgentRunner... cannot be registered to your development team

### ISSUE THREAD

**Issue by Slavianin** [tmobile/stf_ios_support#23]
> note: Using new build system
note: Planning build
2020-02-21 13:18:20.770 xcodebuild[92584:878194]  DVTPortal: Service '<DVTPortalAppIDService: 0x7fc14b0bdc60; action='addAppId'>' encountered an unexpected result code from the portal ('9401')
2020-02-21 13:18:20.771 xcodebuild[92584:878194]  DVTPortal: Error:
Error Domain=DVTPortalServiceErrorDomain Code=9401 "An App ID with Identifier 'com.facebook.WebDriverAgentRunner.xctrunner' is not available. Please enter a different string." UserInfo={payload={
    creationTimestamp = "2020-02-21T11:18:20Z";
    httpCode = 200;
    protocolVersion = QH65B2;
    requestId = "9172F395-1E2E-4CE3-9394-F05E2D528870";
    requestUrl = "https://developerservices2.apple.com/services/QH65B2/ios/addAppId.action";
    responseId = "8a40a192-f113-4175-b0e0-61b8e042b70c";
    resultCode = 9401;
    resultString = "An App ID with Identifier 'com.facebook.WebDriverAgentRunner.xctrunner' is not available. Please enter a different string.";
    userLocale = "en_US";
    userString = "An App ID with Identifier 'com.facebook.WebDriverAgentRunner.xctrunner' is not available. Please enter a different string.";
}, NSLocalizedDescription=An App ID with Identifier 'com.facebook.WebDriverAgentRunner.xctrunner' is not available. Please enter a different string.}
note: Constructing build description
error: Failed to register bundle identifier. The app identifier "com.facebook.WebDriverAgentRunner.xctrunner" cannot be registered to your development team. Change your bundle identifier to a unique string to try again. (in target 'WebDriverAgentRunner' from project 'WebDriverAgent')
error: No profiles for 'com.facebook.WebDriverAgentRunner.xctrunner' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.facebook.WebDriverAgentRunner.xctrunner'. (in target 'WebDriverAgentRunner' from project 'WebDriverAgent')
2020-02-21 13:18:21.235 xcodebuild[92584:878194] Error writing xctestrun file: Error Domain=NSCocoaErrorDomain Code=4 "The folder “WebDriverAgentRunner_iphoneos13.2-arm64e.xctestrun” doesn’t exist." UserInfo={NSFilePath=/Users/test/Library/Developer/Xcode/DerivedData/WebDriverAgent-cnczpjtczqwbycdtrikylgfbbeer/Build/Products/WebDriverAgentRunner_iphoneos13.2-arm64e.xctestrun, NSUserStringVariant=Folder, NSUnderlyingError=0x7fc14b25ca10 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
** TEST BUILD FAILED **

make: *** [bin/wda/build_info.json] Error 65

**Comment by Slavianin** [comment]
I think Make script has some problem when it use config file. 
In my case I need to change signing team in each of xcodeproj and change bundle identifier manually

after manipulations I have 

> mkdir -p offline/repos/stf-ios-provider
rm -rf offline/repos/stf-ios-provider/*
ln -s ../../../repos/stf-ios-provider/node_modules/     offline/repos/stf-ios-provider/node_modules
ln -s ../../../repos/stf-ios-provider/package.json      offline/repos/stf-ios-provider/package.json
ln -s ../../../repos/stf-ios-provider/package-lock.json offline/repos/stf-ios-provider/package-lock.json
ln -s ../../../repos/stf-ios-provider/runmod.js         offline/repos/stf-ios-provider/runmod.js
ln -s ../../../repos/stf-ios-provider/lib/              offline/repos/stf-ios-provider/lib
ln: bin/wda/web: File exists
make: *** [offline/repos/stf-ios-provider] Error 1


then I removed wda folder and tried again 

> Fetching dependencies
Dependencies up-to-date
go get github.com/fsnotify/fsnotify
go get github.com/sirupsen/logrus
go build view_log.go
Traceback (most recent call last):
  File "./get-version-info.sh", line 39, in <module>
    "wdaproxy": git_info( 'repos/wdaproxy', '../..' ),
  File "./get-version-info.sh", line 9, in git_info
    os.chdir( dir )
OSError: [Errno 2] No such file or directory: 'repos/wdaproxy'
make: *** [offline/dist.tgz] Error 1

**Comment by Slavianin** [comment]
after some manipulation, wdaproxy was installed manually too ) 
dist was created and after run it I saw only start / end ffmpeg
@nanoscopic, maybe you can share made dist.tgz ? if it possible, I want to try how it works

**Comment by nanoscopic** [comment]
I got a similar issue as what you show, "The app identifier "com.facebook.WebDriverAgentRunner.xctrunner" cannot be registered to your development team" when attempting to use a non paid apple account to attempt to build WDA. I don't believe it is possible any more, as IOS development of an app can only now be done with a paid developer account.

You can read about it online "Building WebDriverAgent with a personal account". If you figure out how I'd be interested to know as I've never been able to make it work.

Additionally, you need to add a provisioning profile for your device to your apple account in order to build any apps to it. I'd suggest googling "how to create iphone provisioning profile". The process keeps changing when Apple decides to; so I'm never quite clear on what the current process is.

I can share out a dist.tgz minus the built WDA/WebDriverAgent. The account we are using to test is not setup to publish apps to other users, so the WDA we are testing could not be used by others. You'll need to have a paid developer account to create a built WDA that will function with your device.

You can build just the WDA from a fresh clone using `make wda` to avoid all the other issues building everything else.

**Comment by Slavianin** [comment]
@nanoscopic WebDriverAgent was made correctly, I'm opened WebDriverAgent.xcodeproj changed team on myself and changed bundle identifier in IntegrationApp and WebDriverAgentRunner (Build Settings)

But now I have next trouble

> mkdir -p coordinator/icon/stf.iconset
cp coordinator/icon/stf.iconset1/* coordinator/icon/stf.iconset
cp coordinator/icon/stf.iconset2/* coordinator/icon/stf.iconset
iconutil -c icns -o coordinator/icon/stf.icns coordinator/icon/stf.iconset
mkdir -p STF\ Coordinator.app/Contents/MacOS
mkdir -p STF\ Coordinator.app/Contents/Resources
cp coordinator/icon/stf.icns STF\ Coordinator.app/Contents/Resources/icon.icns
cp bin/coordinator STF\ Coordinator.app/Contents/MacOS/
echo '{"config_path":"./config.json"}' > STF\ Coordinator.app/Contents/Resources/config.json
cp coordinator/app/Info.plist STF\ Coordinator.app/Contents/
./get-version-info.sh ios_support > STF\ Coordinator.app/Contents/Resources/build_info.json
./util/signers.pl sign "{apple_team_id}" "STF Coordinator.app"
Could not find Mac Developer cert for developer OU {apple_team_id}
make: *** [STF Coordinator.app] Error 1

**Comment by DavidRayner** [comment]
did you manage to get this working? I'm having the same problem.

**Comment by Slavianin** [comment]
@DavidRayner no, it's last step where I got, but I think It's problem because I don't have apple developer subscription

**Comment by nanoscopic** [comment]
If you open Xcode, go to Preferences, then to the Accounts tab, you can see the various development certificates that you have on your machine there, and use `Manage Certificates` to download more certs ( specifically the Mac developer cert ). The Mac Developer cert is used to sign the app. Note that you don't need the app to run the coordinator.

The app is only needed to run the coordinator as a background process. You can ignore any trouble building the app and just run the coordinator directly within a shell window ( or iterm window as I prefer to )

You can't setup everything without having a paid apple developer account or using a jailbroken ios device. It is not possible. It used to be possible to use Cydia Impactor to sign and deploy apps to an ios device using a regular Apple Developer Account ( unpaid ) but Apple closed that "loophole" over a year ago to my knowledge.

It is as simple as "there is no way to deploy WebDriverAgent to an IOS device without a paid developer account". It's dumb; but that's how it is currently. I've spent time looking for ways around this. There are ways; but you have to jailbreak your device. Even then, I'm not sure if Xcode will happily interact with a WDA deployed via a jailbroken install; it still make not work even then.

**Comment by nanoscopic** [comment]
You need a paid developer account to use stf_ios_support.
