### ISSUE TITLE
Any plans to move to idb? Nope

### ISSUE THREAD

**Issue by EitanBe** [tmobile/stf_ios_support#25]

**Comment by EitanBe** [comment]
https://github.com/facebook/idb
https://www.fbidb.io/

**Comment by nanoscopic** [comment]
I briefly reviewed idb about 5 months ago. I was unable to get it to work controlling real devices. The documentation indicates that it should, and it seems to partially work, but was crashing frequently on any actions with a real device.

I don't think generally Facebook is controlling real devices with either WDA or IDB. The WDA uses by stf_ios_support is altered to make it allow clicking on real devices for example.

There are some minor portions of idb that may prove useful in the long run, but for now it does not provide any benefit and is generally huge.
