### ISSUE TITLE
 Setup had an error Error: Cannot find module 'minimatch'

### ISSUE THREAD

**Issue by bikeebh** [tmobile/stf_ios_support#26]
Hi @nanoscopic 

When I running ./run command
i am getting this log 

 ./run 
INFO[0000] Process start - device_trigger                proc=device_trigger type=proc_start
INFO[0000] Process start - video_enabler                 proc=video_enabler type=proc_start
INFO[0000] Process start - stf_provider                  client_hostname=radmins-Mac-mini.local client_ip=172.16.50.111 proc=stf_provider server_hostname=radmins-Mac-mini.local server_ip=172.16.50.111 type=proc_start
INFO[0000] New Interface                                 class=ff subclass=fd type=iface_body uuid=234b815bdb07c102d31cb1899729734eb38a4d83
WARN[0000] Process end - stf_provider                    proc=stf_provider type=proc_end
INFO[0000] Process start - stf_provider                  client_hostname=radmins-Mac-mini.local client_ip=172.16.50.111 proc=stf_provider server_hostname=radmins-Mac-mini.local server_ip=172.16.50.111 type=proc_start
INFO[0000] New Interface                                 class=ff subclass=fe type=iface_body uuid=234b815bdb07c102d31cb1899729734eb38a4d83
INFO[0000] New Interface                                 class=06 subclass=01 type=iface_body uuid=234b815bdb07c102d31cb1899729734eb38a4d83
WARN[0000] Process end - stf_provider                    proc=stf_provider type=proc_end
INFO[0000] Device object created                         dev_ios_port=9240 dev_name=me_bikee dev_uuid=234b815bdb07c102d31cb1899729734eb38a4d83 type=devd_create vid_port=8000 vnc_port=5901 wda_port=8100
INFO[0000] Device connected                              dev_name=me_bikee dev_uuid=234b815bdb07c102d31cb1899729734eb38a4d83 type=dev_connect
INFO[0000] Process start - ffmpeg                        ops="[-f avfoundation -i me_bikee -pixel_format bgr0 -f mjpeg -bsf:v mjpegadump -bsf:v mjpeg2jpeg -r 5 -vsync 2 -nostats pipe:1]" proc=ffmpeg type=proc_start uuid=234b815bdb07c102d31cb1899729734eb38a4d83
INFO[0000] Process start - mirrorfeed                    mirrorfeed_bin=bin/mirrorfeed pipe=video_pipes/pipe_8000 port=8000 proc=mirrorfeed tunName=en0 type=proc_start uuid=234b815bdb07c102d31cb1899729734eb38a4d83
INFO[0000] New Interface                                 class=06 subclass=01 type=iface_body uuid=234b815bdb07c102d31cb1899729734eb38a4d83
INFO[0000] New Interface                                 class=ff subclass=2a type=iface_body uuid=234b815bdb07c102d31cb1899729734eb38a4d83
INFO[0000] Video - interface available                   dev_name=me_bikee dev_uuid=234b815bdb07c102d31cb1899729734eb38a4d83 type=vid_interface
INFO[0000] New Interface                                 class=ff subclass=fe type=iface_body uuid=234b815bdb07c102d31cb1899729734eb38a4d83
INFO[0002] Process start - stf_provider                  client_hostname=radmins-Mac-mini.local client_ip=172.16.50.111 proc=stf_provider server_hostname=radmins-Mac-mini.local server_ip=172.16.50.111 type=proc_start
WARN[0002] Process end - stf_provider                    proc=stf_provider type=proc_end
INFO[0007] Process start - stf_provider                  client_hostname=radmins-Mac-mini.local client_ip=172.16.50.111 proc=stf_provider server_hostname=radmins-Mac-mini.local server_ip=172.16.50.111 type=proc_start
WARN[0007] Process end - stf_provider                    proc=stf_provider type=proc_end
INFO[0017] Process start - stf_provider                  client_hostname=radmins-Mac-mini.local client_ip=172.16.50.111 proc=stf_provider server_hostname=radmins-Mac-mini.local server_ip=172.16.50.111 type=proc_start
WARN[0017] Process end - stf_provider                    proc=stf_provider type=proc_end

and When I checking the log  of **stf_device_ios**

./view_log -proc stf_device_ios

020-02-27T07:01:08.985Z INF/device:support:push 83378 [234b815bdb07c102d31cb1899729734eb38a4d83] Sending output to "tcp://172.16.50.111:7270"
2020-02-27T07:01:08.987Z INF/device 83378 [234b815bdb07c102d31cb1899729734eb38a4d83] Preparing device
2020-02-27T07:01:09.031Z FTL/device 83378 [234b815bdb07c102d31cb1899729734eb38a4d83] Setup had an error Error: Cannot find module 'minimatch'
Require stack:
- /Users/radmin/stf_ios_support/repos/stf-ios-provider/lib/util/grouputil.js
- /Users/radmin/stf_ios_support/repos/stf-ios-provider/lib/units/device-ios/plugins/group.js
- /Users/radmin/stf_ios_support/repos/stf-ios-provider/lib/units/device-ios/index.js
- /Users/radmin/stf_ios_support/repos/stf-ios-provider/lib/cli/device-ios/index.js
- /Users/radmin/stf_ios_support/repos/stf-ios-provider/lib/cli/index.js
- /Users/radmin/stf_ios_support/repos/stf-ios-provider/runmod.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/radmin/stf_ios_support/repos/stf-ios-provider/lib/util/grouputil.js:5:17)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/radmin/stf_ios_support/repos/stf-ios-provider/lib/units/device-ios/plugins/group.js:9:17)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
2020-02-27T07:01:09.032Z FTL/util:lifecycle 83378 [234b815bdb07c102d31cb1899729734eb38a4d83] Shutting down due to fatal error

This module **minimatch** is already install in my machine

inside /usr/local/lib/node_modules/minimatch

What could be the issue?

**Comment by nanoscopic** [comment]
My guess on what caused this was an incomplete build due to errors while running `make`. Specifically, this would occur if the `npm install` step within `repos/stf-ios-provider` was not run.

As it has been closed by the opener, I assume that was the case, and self-resolved when the `make` process went farther / completed without error.
