### ISSUE TITLE
Issues running the provider

### ISSUE THREAD

**Issue by rajen00** [tmobile/stf_ios_support#28]
Hi, First of all, thanks for the great work!!! 
I keep on getting the following error message while running Make dist
found 3 vulnerabilities (1 low, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details
mkdir -p offline/repos/stf-ios-provider
rm -rf offline/repos/stf-ios-provider/*
ln -s ../../../repos/stf-ios-provider/node_modules/     offline/repos/stf-ios-provider/node_modules
ln -s ../../../repos/stf-ios-provider/package.json      offline/repos/stf-ios-provider/package.json
ln -s ../../../repos/stf-ios-provider/package-lock.json offline/repos/stf-ios-provider/package-lock.json
ln -s ../../../repos/stf-ios-provider/runmod.js         offline/repos/stf-ios-provider/runmod.js
ln -s ../../../repos/stf-ios-provider/lib/              offline/repos/stf-ios-provider/lib
ln: bin/wda/web: File exists
make: *** [offline/repos/stf-ios-provider] Error 1

-----------------------------------------------------------------
After individually running the Make commands got the dist.tar created. But on executing the run script it  errored out.
rajenbanerjee@MacBook-Pro dist % ./run
Unable to open file for writing: open logs/coordinator: no such file or directoryUnable to open file for writing: open logs/procs: no such file or directoryCannot write to logfile: invalid argumentFailed to fire hook: invalid argument
INFO[0000] Process start - device_trigger                proc=device_trigger type=proc_start
INFO[0000] Process start - stf_provider                  client_hostname=MacBook-Pro.local client_ip=192.168.1.8 proc=stf_provider server_hostname=localhost server_ip=127.0.0.1 type=proc_start
INFO[0000] Process start - video_enabler                 proc=video_enabler type=proc_start

The directories are all there. Not sure what the issue is.

**Comment by nanoscopic** [comment]
I've committed a minor update to the repo to avoid the `bin/wda/web: File exists` error. That shouldn't break anything but you won't the error won't occur any more with the update.

If you are running `./run` locally in the same place you built everything, you don't need to use or anything with `dist.tgz`, so you won't need to run `make dist`. You can simply run it directly from where you built it.

You can, of course, also extract the dist.tgz somewhere else and use that but it is not required.

The error you are getting about the logs is saying that you have no `logs` folder within the `dist` folder you extracted `dist.tgz` to. This line of the Makefile creates a logs/openvpn.log file that gets saved into dist.tgz: https://github.com/tmobile/stf_ios_support/blob/master/Makefile#L198

When dist.tgz is extracted you should then have an empty openvpn.log file at `dist/logs/openvpn.log` That file is not used if you aren't using VPN, but it serves to ensure that a logs directory is created. Do you have one? If not you can create one.

Also, the error you've shown says that logs/coordinator cannot be created. Perhaps it is a permission issue? You might wish to try `touch logs/coordinator` to create an empty file there before starting up the coordinator to see if that makes any difference.

**Comment by rajen00** [comment]
Thanks David.
Just tried everything afresh.
Ran the Make command. It error out "Could not find Mac Developer cert for developer OU".  This happened while signing the coordinator.app
./util/signers.pl sign "3T877F578Y" "STF Coordinator.app"
Could not find Mac Developer cert for developer OU xxxxxxx

I can confirm that the cert is added in my local keychain. Is there any where else i need to p.lace the cert?
Is there something that i am missing. Do i need to add the certificate somewhere else?

**Comment by nanoscopic** [comment]
For the "app" to be build from CLI / make, the appropriate developer settings must first be manually configured within Xcode.

Xcode:
1. Go to Preferences
2. Accounts Tab
3. Select / add your Apple paid developer account
4. Manage Ceritifcates

See https://help.apple.com/xcode/mac/current/#/dev154b28f09

Strictly speaking, you don't need the app at all. I'd recommend avoiding the App unless you have some specific need for it. Just run the coordinator directly without the App.

If you just remove the word "app" from the end of the first line of stf_ios_support/Makefile then all building of and errors regarding the "STF Coordinator.app" will go away.
