### ISSUE TITLE
PR Proposal: Install .ipa via web ui

### ISSUE THREAD

**Issue by neofreko** [tmobile/stf_ios_support#34]
Looking at the fact that we cannot yet install `.ipa` in the same fashion as `.apk` from the stf dashboard (CMIIW), I would like to create a proposal to start working on this. Eventually, I would like to create PR against `openstf/stf` repo. I put the proposal here as people will be looking into this repo to get iOS working in openSTF.

The following are the changes I have identified to be added into `openstf/stf`:

1. The dashboard need to whitelist .ipa file when uploading
2. `manifest` task (`lib/units/storage/plugins/apk/task`) need to produce manifest from .ipa
3. `install` service (`lib/units/device/plugins`) need to:
     a.  handle the `.ipa` manifest. Includes pushing the binary to the device and launching the app
     b. handle uninstall request

I have some work in progress for the second part here: https://github.com/neofreko/stf/tree/feature/ipa-install

Any feedback would be much appreciated 😄

**Comment by nanoscopic** [comment]
Sounds good. Do you stf_ios_support up and working with your STF server already?

This is a feature that is certainly needed and we welcome your contribution.

I am not sure as to the status of anything being contributed into openstf/stf yet. The project leaders are currently in a transition period of sorts before integrating IOS changes upstream. More information should be out soon about this.

Suffice it to say, OpenSTF will be accepting changes to enable IOS in the near future.

In the mean time, feel free to contribute your changes into https://github.com/nanoscopic/stf-ios-provider ; that is the provider itself fractured out from the main codebase to reduce dependencies and make it simpler to build / develop

**Comment by neofreko** [comment]
@nanoscopic 
Hi, thank you for the kind response.

Yes. I have stf_ios_support and STF server up already. Up to this minute, I have been able to install the ipa file onto the device. To complete the launch sequence, I probably have to switch from `ios-deploy` to `appium-idb`. That will complete the MVP.

As I've mentioned above, there has been minimum changes made on the `openstf/stf` side (for MVP scope). The rest of the code currently resides on `stf_ios_provider`.

I will close this issue and file PR on `stf_ios_provider`.
