### ISSUE TITLE
STF Dashboard not visible.

### ISSUE THREAD

**Issue by upendra6oct** [tmobile/stf_ios_support#36]
Guys not able to get dasbord.
Please let me know how to get that.

**Comment by nanoscopic** [comment]
I don't understand the question. What is a "STF Dashboard"? Do you mean the OpenSTF frontend showing the list / icons of your connected devices?

If so, you need to first start a STF server somewhere, have a host pointed to the IP address of where the server is running, then you can open that page in a browser.

**Comment by upendra6oct** [comment]
Thanks got that.
