### ISSUE TITLE
System dialog boxes cannot be interacted with

### ISSUE THREAD

**Issue by jdoxey** [tmobile/stf_ios_support#43]
When the phone displays an alert box with multiple options, tapping any of the alert buttons in STF is treated as though you tapped "Cancel".
Have you seen this before?

**Comment by jdoxey** [comment]
Maybe because of this: https://github.com/facebookarchive/WebDriverAgent/issues/1082

**Comment by nanoscopic** [comment]
Not only can the buttons not be properly clicked on system dialog boxes; you also cannot enter text into them. If you click on the field to enter text it just closes the dialog box.

**Comment by nanoscopic** [comment]
In the latest stf_ios_support and latest STF server, this is now supported by way of a button in the advanced section that pops up a dialog that can be clicked to respond to an alert properly. This server docker image can be used: https://hub.docker.com/r/livxtrm/devicefarmer

Combine that with https://github.com/tmobile/stf_ios_support to get support for this.

**Comment by chriiis78** [comment]
Actually, I can click on the popup when I use the wda/touch/perform in stf-ios-provider and is a lot faster.
`plugin.PostData('wda/touch/perform',{"actions":[{"action":"tap","options":{"x":x,"y":y}}]},true)`

**Comment by nanoscopic** [comment]
@chriiis78 This is actually tremendously helpfully and solves so many problems. Thank you.

**Comment by chriiis78** [comment]
I’m glad it helped you! I also used it for swipe if you think it useful https://github.com/chriiis78/stf-ios-provider/blob/1fb20716193b069f64b72fabc8fc9c8328709110/lib/units/device-ios/plugins/wdaCommands.js#L99

**Comment by nanoscopic** [comment]
@chriiis78 10x yes also helpful. That was my very next thought was how to do swipe/drag with it. Thanks also.
