### ISSUE TITLE
unable to run openstf server

### ISSUE THREAD

**Issue by gkrananth** [tmobile/stf_ios_support#54]
i am getting error on while running docker-compose up

server_nginx_1 exited with code 1

**Comment by gkrananth** [comment]
i am able to run the server.  How to access the client from outside network means using public ip.

**Comment by nanoscopic** [comment]
These two lines of configuration expose the nginx container on ports 80 and 443: https://github.com/tmobile/stf_ios_support/blob/master/server/docker-compose.yml#L17

Exposed ports are bound on all available interfaces by default of the machine that is running docker-compose. So they will be available on the IPs of that machine.

**Comment by gkrananth** [comment]
i have already success on launching the server and client. But am facing the video/iphone ui not showing in stf dash board.  Can you please help me on this.

**Comment by nanoscopic** [comment]
Closing as you've already opened separate issue, and are saying that you are able to run the openstf server.
