### ISSUE TITLE
Keyboard Support

### ISSUE THREAD

**Issue by nanoscopic** [tmobile/stf_ios_support#7]
Typing via the keyboard in STF does not work currently on real devices. It should work already on simulated IOS devices once those are supported, but cannot test it as starting simulated devices has not been made possible yet with stf_ios_support.

The code to make the keyboard work was already copied into the codebase ( into stf device-ios unit ) but it doesn't work. It was copied from the mrx repo. The only reason I can believe it would be in that repo is that I think that repo must be primarily meant to work with simulators not real devices.

**Comment by nanoscopic** [comment]
The latest changes enable clicking by using Veency app on jailbroken IOS devices. Veency also has keyboard support. Support for keyboard through Veency will be added so that users who are okay with jailbreaking their devices can also get faster / functional keyboard support.

**Comment by nanoscopic** [comment]
Keyboard functionality does work through the port 8100 interface on the WDA currently being built by stf_ios_support. This will be connected through to STF. Still TODO; but coming soon.

**Comment by passcodex** [comment]
> Keyboard functionality does work through the port 8100 interface on the WDA currently being built by stf_ios_support. This will be connected through to STF. Still TODO; but coming soon.

@nanoscopic 
Thank will great, on the other side, if I use veency, can I use veency on iOS 13.4?

**Comment by nanoscopic** [comment]
Keyboard works now. Backspace and enter are supported also. Left/right cursor keys swipe screen left and right respectively.
